import { db } from "../db";
import { termsAndConditions } from "../../shared/schema";

const defaultTermsContent = `# Rev Winner – Terms & Conditions

## 1. Introduction

Welcome to Rev Winner ("Platform", "Service"). By accessing or using this Platform, you agree to be bound by these Terms & Conditions.

Rev Winner is a SaaS-based sales intelligence and productivity tool. The platform provides AI-powered assistance, meeting intelligence, and real-time sales enablement features.

**If you do not agree with these terms, please do not use the platform.**

---

## 2. Eligibility

Users must be at least 18 years of age to use this platform and must provide accurate registration information.

---

## 3. Account & Access

- Users are responsible for maintaining confidentiality of login credentials.
- Sharing accounts or unauthorized access is strictly prohibited.
- Rev Winner reserves the right to suspend accounts for suspicious activity or policy violations.

---

## 4. Subscription & Payment

- All paid plans require advance payment.
- Subscription will auto-renew unless canceled by the user.
- Prices are subject to change with prior notice.

---

## 5. Cancellation Policy

- Users may cancel their subscription anytime from the account dashboard or by contacting support@revwinner.com.
- Once canceled, access will remain active till the end of the billing cycle.
- Cancellation does not automatically initiate a refund unless eligible under refund terms.

---

## 6. Refund Policy

Rev Winner provides a 3-session free trial.

No refunds will be issued after subscription activation, except in cases of:
- Duplicate payment charged
- Technical billing error by Rev Winner
- Subscription purchased but service not used at all and request submitted within 7 days

Refund eligibility is at the discretion of Rev Winner management.

Refunds, if approved, will be processed within 7-14 business days back to the original payment method.

---

## 7. Privacy Policy

Rev Winner values user privacy and follows industry-standard security practices.

### Data We Collect
- Name, Email, Contact details (provided by user)
- Usage logs for product improvement & billing
- AI interaction logs only for usage metering, not stored for training or sale
- We do not store meeting audio or conversation content unless explicitly enabled by the user

### How We Use Data
- Authentication & user verification
- Billing and usage analytics
- Enhancing product performance
- Customer support and security monitoring

### Data Security
- Encrypted storage and secure access policies are enforced.
- Users may request data export or deletion (subject to account validation).

**We do not sell user data to third parties.**

---

## 8. Shipping / Delivery Policy

- Rev Winner is a cloud-based digital product.
- No physical shipping required.
- Access is delivered instantly upon successful sign-up.
- Support and feature updates are delivered online.

If you face access issues after payment, contact: support@revwinner.com

---

## 9. Intellectual Property

All platform content, branding, code, and assets belong to Rev Winner. Users may not reverse engineer, copy, or resell the platform.

---

## 10. Fair Use & Restrictions

Users must not:
- Use the platform for illegal or unethical activity
- Attempt to extract, clone, or misuse AI models
- Share proprietary platform outputs commercially without consent

---

## 11. Disclaimer & Limitation of Liability

Rev Winner is a productivity tool. It does not guarantee revenue results or business outcomes.

The service is provided "as-is" without warranty.

---

## 12. Product Maturity, Accuracy & Experimental Features

Rev Winner is an evolving AI-powered platform. While several core features are stable and production-ready, certain features are currently in an experimental or early-stage release phase and may continue to improve over time.

Due to the nature of artificial intelligence and machine-learning systems, outputs generated by Rev Winner may occasionally contain inaccuracies, incomplete information, or unexpected behavior. Accuracy, performance, and reliability may vary based on usage, data inputs, configurations, and ongoing model improvements.

**By signing up for and using Rev Winner, you acknowledge and agree that:**
- Some features may be in beta, experimental, or under active development
- Feature behavior, accuracy levels, and performance may evolve over time
- Temporary limitations, inaccuracies, or changes may occur as the platform continues to mature
- Rev Winner does not guarantee absolute accuracy or uninterrupted availability at all times

Rev Winner is continuously working to enhance platform stability, accuracy, and feature reliability. Updates, improvements, and refinements will be rolled out periodically without prior notice as part of ongoing development.

**By proceeding with registration and usage of the platform, you confirm that you understand and accept the current state of the product and agree to use it accordingly.**

---

## 13. Updates to Terms

Rev Winner may update these terms periodically. Continued use indicates acceptance of updates.

---

## 14. Contact Information

For support or policy inquiries:
📧 support@revwinner.com

---

*Last updated: January 2025*`;

async function createDefaultTerms() {
  try {
    console.log("Creating default terms and conditions...");
    
    // Check if terms already exist
    const existingTerms = await db.select().from(termsAndConditions).limit(1);
    
    if (existingTerms.length > 0) {
      console.log("Terms and conditions already exist. Skipping creation.");
      console.log("Existing terms count:", existingTerms.length);
      return;
    }
    
    console.log("No existing terms found. Creating default terms...");
    
    // Create default terms
    const [newTerms] = await db.insert(termsAndConditions).values({
      title: "Rev Winner – Terms & Conditions",
      content: defaultTermsContent,
      version: "1.0",
      isActive: true,
      lastModifiedBy: "system", // System-generated default
    }).returning();
    
    console.log("✅ Default terms and conditions created successfully!");
    console.log("Terms ID:", newTerms.id);
    console.log("Version:", newTerms.version);
    console.log("Title:", newTerms.title);
    
  } catch (error) {
    console.error("❌ Error creating default terms:", error);
    throw error;
  }
}

// Run the script if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  createDefaultTerms()
    .then(() => {
      console.log("🎉 Script completed successfully!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("💥 Script failed:", error);
      process.exit(1);
    });
}

export { createDefaultTerms };